Modify negative test cases to fail on error code 2

diff --git a/tests/patch/err_exit b/tests/patch/err_exit
--- a/tests/patch/err_exit
+++ b/tests/patch/err_exit
@@ -1,5 +1,5 @@
 #!/bin/bash
 
 echo "FATAL ERROR: return code $err" >&2
-echo "FATAL ERROR: $1" >&2
+echo "FATAL ERROR: $msg" >&2
 exit $err
